zip_url: https://github.com/ExpressionAnalysis/HLAProfiler/zipball/master
tar_url: https://github.com/ExpressionAnalysis/HLAProfiler/tarball/master
theme: jekyll-theme-architect
repository: ExpressionAnalysis/HLAProfiler
show_downloads: true
gems:
  - jekyll-seo-tag
